#!/usr/bin/env bun
// Generates docs/history/decisions-log.md from the GSD-era planning tree.
// Run from the repo root while .planning/ still exists:
//   bun docs/history/tools/extract-decisions.ts > docs/history/decisions-log.md
import { existsSync, readdirSync, readFileSync, statSync } from "node:fs";
import { join } from "node:path";

const root = process.cwd();
// Plan summaries live in two roots: .planning/phases/ for most milestones, and
// .planning/milestones/v2.8-phases/ for v2.8, whose phase directories were archived under the
// milestone instead of being left in the shared tree.
const phaseRoots = [".planning/phases", ".planning/milestones/v2.8-phases"];

type Entry = { phase: string; plan: string; decisions: string[] };

function walkSummaries(dir: string, out: string[]): void {
  for (const name of readdirSync(dir)) {
    const p = join(dir, name);
    if (statSync(p).isDirectory()) walkSummaries(p, out);
    else if (name.endsWith("-SUMMARY.md")) out.push(p);
  }
}

function frontmatter(text: string): string {
  const m = text.match(/^---\n([\s\S]*?)\n---/);
  return m ? m[1] : "";
}

function field(fm: string, key: string): string {
  const m = fm.match(new RegExp(`^${key}:\\s*(.*)$`, "m"));
  return m ? m[1].trim() : "";
}

function keyDecisions(fm: string): string[] {
  const lines = fm.split("\n");
  const start = lines.findIndex((l) => /^key-decisions:/.test(l));
  if (start === -1) return [];
  const out: string[] = [];
  for (const l of lines.slice(start + 1)) {
    if (/^\S/.test(l)) break; // next top-level key
    const m = l.match(/^\s+-\s+"?(.*?)"?\s*$/);
    if (m && m[1]) out.push(m[1]);
  }
  return out;
}

const files: string[] = [];
for (const rel of phaseRoots) {
  const abs = join(root, rel);
  if (existsSync(abs)) walkSummaries(abs, files);
}
const entries: Entry[] = [];
for (const f of files.sort()) {
  const fm = frontmatter(readFileSync(f, "utf8"));
  const decisions = keyDecisions(fm);
  if (decisions.length === 0) continue;
  entries.push({ phase: field(fm, "phase") || f, plan: field(fm, "plan") || "?", decisions });
}

const byPhase = new Map<string, Entry[]>();
for (const e of entries) byPhase.set(e.phase, [...(byPhase.get(e.phase) ?? []), e]);

const phaseOrder = [...byPhase.keys()].sort((a, b) => parseFloat(a) - parseFloat(b));
const total = entries.reduce((n, e) => n + e.decisions.length, 0);

const lines: string[] = [];
lines.push("# Decisions log — v1 to v2.9");
lines.push("");
lines.push(`<!-- Generated by docs/history/tools/extract-decisions.ts on ${new Date().toISOString().slice(0, 10)} from ${files.length} plan summaries; ${total} per-plan decisions. Do not edit by hand. -->`);
lines.push("");
lines.push("Every decision recorded during the GSD-era build, in three parts: per-plan decisions from the plan summaries (A), the project-level Key Decisions table (B), and the design-vision decisions log (C). The ADRs under `docs/adr/` distil the architectural ones; this file keeps all of them.");
lines.push("");
lines.push("## A. Per-plan decisions, by phase");
lines.push("");
for (const phase of phaseOrder) {
  lines.push(`### Phase ${phase}`);
  lines.push("");
  for (const e of byPhase.get(phase)!.sort((x, y) => x.plan.localeCompare(y.plan))) {
    lines.push(`**Plan ${e.plan}**`);
    for (const d of e.decisions) lines.push(`- ${d}`);
    lines.push("");
  }
}

function tableAfterHeading(file: string, heading: string): string {
  const text = readFileSync(join(root, file), "utf8");
  const start = text.indexOf(heading);
  if (start === -1) throw new Error(`heading not found: ${heading} in ${file}`);
  const rest = text.slice(start + heading.length);
  const rows = rest.split("\n").filter((l) => l.startsWith("|"));
  // stop at the first non-table line after the table began
  const out: string[] = [];
  let began = false;
  for (const l of rest.split("\n")) {
    if (l.startsWith("|")) { began = true; out.push(l); }
    else if (began && l.trim() === "") break;
    else if (began) break;
  }
  return out.length ? out.join("\n") : rows.join("\n");
}

lines.push("## B. Project Key Decisions (PROJECT.md, as of 2026-02-20)");
lines.push("");
lines.push(tableAfterHeading(".planning/PROJECT.md", "## Key Decisions"));
lines.push("");
lines.push("## C. Design Decisions Log (design-vision.md)");
lines.push("");
lines.push(tableAfterHeading("docs/history/specs/design-vision.md", "## Design Decisions Log"));
lines.push("");
process.stdout.write(lines.join("\n"));
