#!/usr/bin/env bun
// Generates docs/history/phases.md from the archived roadmaps, the v2.9
// roadmap and the per-phase verification reports.
//   bun docs/history/tools/extract-phases.ts > docs/history/phases.md
import { existsSync, readdirSync, readFileSync } from "node:fs";
import { join } from "node:path";

const root = process.cwd();
const archives = join(root, "docs", "history", "milestones");
const phasesDir = join(root, ".planning", "phases");

type Phase = { num: string; name: string; goal: string; plans: number; status: string; score: string; human: string[] };
type Milestone = { title: string; phases: Phase[] };

function parseRoadmap(text: string, milestoneTitle: string): Milestone {
  const phases: Phase[] = [];
  const blocks = text.split(/\n(?=### Phase )/);
  for (const b of blocks) {
    // Phase ids are numeric ("84", "22.1") except v1's "e2e-verification"; goals are written
    // "**Goal**:" in most roadmaps and "**Goal:**" in v2.0's; plan counts are checkbox lines in
    // v2.9's roadmap and a "**Plans:** N plans" line in the archived ones.
    const h = b.match(/^### Phase ([\w.-]+): (.+?)(?: — DEFERRED| -- DEFERRED)?\s*$/m);
    if (!h) continue;
    const goal = (b.match(/\*\*Goal:?\*\*:?\s*(.+)/) ?? [])[1]?.trim() ?? "";
    const checked = (b.match(/^- \[[ x]\] .*PLAN\.md/gm) ?? []).length;
    const declared = Number((b.match(/\*\*Plans:?\*\*:?\s*(\d+)/) ?? [])[1] ?? 0);
    const plans = checked || declared;
    const nameRaw = h[2].trim();
    const name = /DEFERRED/i.test(h[0]) && !/DEFERRED/i.test(nameRaw) ? `${nameRaw} (deferred)` : nameRaw;
    phases.push({ num: h[1], name, goal, plans, status: "", score: "", human: [] });
  }
  return { title: milestoneTitle, phases };
}

const milestones: Milestone[] = [];
for (const f of readdirSync(archives).filter((n) => /-ROADMAP\.md$/.test(n)).sort((a, b) => parseFloat(a.replace(/^v/, "")) - parseFloat(b.replace(/^v/, "")))) {
  const text = readFileSync(join(archives, f), "utf8");
  const title = (text.match(/^## (v[\d.]+ .+?)(?: \(Shipped.*)?$/m) ?? [])[1] ?? f.replace("-ROADMAP.md", "");
  milestones.push(parseRoadmap(text, title));
}
{
  const text = readFileSync(join(root, ".planning", "ROADMAP.md"), "utf8");
  const v29 = text.slice(text.indexOf("## v2.9"));
  milestones.push(parseRoadmap(v29, "v2.9 Platform Completion (executed 2026-02-20 → 2026-02-23, never archived)"));
}

// verification reports
const dirs = existsSync(phasesDir) ? readdirSync(phasesDir) : [];
for (const m of milestones) for (const p of m.phases) {
  const dir = dirs.find((d) => d.startsWith(`${p.num}-`) && existsSync(join(phasesDir, d, `${p.num}-VERIFICATION.md`)));
  if (!dir) continue;
  const v = readFileSync(join(phasesDir, dir, `${p.num}-VERIFICATION.md`), "utf8");
  p.status = (v.match(/^status:\s*(.+)$/m) ?? [])[1] ?? "";
  p.score = (v.match(/^score:\s*(.+)$/m) ?? [])[1] ?? "";
  const hv = v.split("### Human Verification Required")[1];
  if (hv) p.human = [...hv.matchAll(/^#### \d+\.\s*(.+)$/gm)].map((x) => x[1].trim());
}

const total = milestones.reduce((n, m) => n + m.phases.length, 0);
const out: string[] = [];
out.push("# Phases — v1 to v2.9");
out.push("");
out.push(`<!-- Generated by docs/history/tools/extract-phases.ts on ${new Date().toISOString().slice(0, 10)}: ${total} phases across ${milestones.length} milestones. Do not edit by hand. -->`);
out.push("");
out.push("One line per phase: what it set out to do, how many plans it took, and what the verification report concluded. Verification status is from each phase's `*-VERIFICATION.md` (`passed`, `gaps_found`, `human_needed`, or blank when no report exists). Human-verification items are the checks a person still has to do; they are tracked as Rikmorn/aesir#14.");
out.push("");
for (const m of milestones) {
  out.push(`## ${m.title}`);
  out.push("");
  out.push("| Phase | Name | Goal | Plans | Verification |");
  out.push("|---|---|---|---|---|");
  for (const p of m.phases) {
    const ver = p.status ? `${p.status}${p.score ? ` (${p.score})` : ""}` : "—";
    out.push(`| ${p.num} | ${p.name} | ${p.goal.replace(/\|/g, "\\|")} | ${p.plans} | ${ver} |`);
  }
  const withHuman = m.phases.filter((p) => p.human.length);
  if (withHuman.length) {
    out.push("");
    out.push("Human verification still open:");
    for (const p of withHuman) for (const h of p.human) out.push(`- Phase ${p.num}: ${h}`);
  }
  out.push("");
}
process.stdout.write(out.join("\n"));
