/**
 * Commit and PR Node
 *
 * LangGraph node that commits generated files and opens a pull request.
 * Uses factory pattern for dependency injection of GitHub and Linear clients.
 *
 * This is the final node in the successful path of the dev workflow -
 * it commits the generated code, opens a PR, and updates Linear status to Done.
 */

import type { Octokit } from "@octokit/rest";
import type { LinearClient } from "@linear/sdk";
import {
  createCommit,
  createPullRequest,
} from "../../integrations/github/index.js";
import {
  updateIssueStatus,
  emitResponse,
} from "../../integrations/linear/index.js";
import type { DevWorkflowStateType } from "../../state/dev-workflow-state.js";

/**
 * GitHub repository configuration for commit and PR operations
 */
export interface CommitPRConfig {
  /** Repository owner (user or organization) */
  owner: string;
  /** Repository name */
  repo: string;
  /** Base branch for PR (default: 'main') */
  baseBranch: string;
}

/**
 * Factory function to create the commit/PR node with injected dependencies.
 *
 * @param octokit - Authenticated Octokit instance
 * @param linearClient - Authenticated LinearClient instance
 * @param config - GitHub repository configuration
 * @returns LangGraph node function
 */
export function createCommitPRNode(
  octokit: Octokit,
  linearClient: LinearClient,
  config: CommitPRConfig
) {
  /**
   * Commit and PR node - commits files and opens a pull request.
   *
   * @param state - Current workflow state with files and branch
   * @returns Partial state update with PR number and complete status
   */
  return async function commitPRNodeFn(
    state: DevWorkflowStateType
  ): Promise<Partial<DevWorkflowStateType>> {
    // Convert FileChange[] to format for createCommit
    // Filter out delete operations (handled differently in Git Data API)
    const files = state.files
      .filter((f) => f.operation !== "delete")
      .map((f) => ({ path: f.path, content: f.content }));

    // Get first line of task description for PR title
    const titleLine = state.taskDescription.split("\n")[0] || state.taskId;

    // Create commit with all files
    await createCommit(octokit, {
      owner: config.owner,
      repo: config.repo,
      branch: state.branchName!,
      message: `feat: implement ${state.taskId}`,
      files,
    });

    // Create pull request
    const pr = await createPullRequest(octokit, {
      owner: config.owner,
      repo: config.repo,
      title: `[${state.taskId}] ${titleLine}`,
      body: `Implements ${state.taskId}\n\nGenerated by Dev Agent.`,
      head: state.branchName!,
      base: config.baseBranch,
    });

    // Update Linear status to Done
    await updateIssueStatus(linearClient, state.taskId, "Done");

    // Emit response with PR link in Linear UI
    await emitResponse(linearClient, state.taskId, `Opened PR: ${pr.url}`);

    // Return state update with PR number for downstream consumers
    return {
      status: "complete",
      prNumber: pr.number,
    };
  };
}
