/**
 * Tests for Commit and PR Node
 */

import { describe, it, expect, vi, beforeEach } from "vitest";
import { createCommitPRNode, type CommitPRConfig } from "./commit-pr.js";
import type { DevWorkflowStateType } from "../../state/dev-workflow-state.js";

// Mock the GitHub integration module
vi.mock("../../integrations/github/index.js", () => ({
  createCommit: vi.fn(),
  createPullRequest: vi.fn(),
}));

// Mock the Linear integration module
vi.mock("../../integrations/linear/index.js", () => ({
  updateIssueStatus: vi.fn(),
  emitResponse: vi.fn(),
}));

import { createCommit, createPullRequest } from "../../integrations/github/index.js";
import { updateIssueStatus, emitResponse } from "../../integrations/linear/index.js";

const mockCreateCommit = vi.mocked(createCommit);
const mockCreatePullRequest = vi.mocked(createPullRequest);
const mockUpdateIssueStatus = vi.mocked(updateIssueStatus);
const mockEmitResponse = vi.mocked(emitResponse);

describe("createCommitPRNode", () => {
  // Mock clients
  const mockOctokit = {} as Parameters<typeof createCommitPRNode>[0];
  const mockLinearClient = {} as Parameters<typeof createCommitPRNode>[1];

  // Config for tests
  const config: CommitPRConfig = {
    owner: "test-owner",
    repo: "test-repo",
    baseBranch: "main",
  };

  // Base state for tests
  const baseState: DevWorkflowStateType = {
    taskId: "ABC-123",
    taskDescription: "Implement feature X\n\nDetailed description here",
    repositoryUrl: null,
    branchName: "dev-agent/ABC-123",
    files: [
      { path: "src/feature.ts", content: "export const x = 1;", operation: "create" },
      { path: "src/index.ts", content: "export * from './feature.js';", operation: "update" },
    ],
    testResult: { passed: true, exitCode: 0, stdout: "All tests passed", stderr: "", summary: "2 tests passed" },
    testAttempts: 1,
    status: "testing",
    error: null,
    prNumber: null,
  };

  beforeEach(() => {
    vi.clearAllMocks();
  });

  it("should commit all non-delete files", async () => {
    mockCreateCommit.mockResolvedValue({
      sha: "abc123",
      message: "feat: implement ABC-123",
      author: { name: "Agent", email: "agent@example.com", date: "2024-01-01" },
    });
    mockCreatePullRequest.mockResolvedValue({
      number: 42,
      title: "[ABC-123] Implement feature X",
      body: "Implements ABC-123\n\nGenerated by Dev Agent.",
      state: "open",
      headBranch: "dev-agent/ABC-123",
      baseBranch: "main",
      url: "https://github.com/test-owner/test-repo/pull/42",
    });
    mockUpdateIssueStatus.mockResolvedValue(undefined);
    mockEmitResponse.mockResolvedValue(undefined);

    const commitPRNode = createCommitPRNode(mockOctokit, mockLinearClient, config);
    await commitPRNode(baseState);

    expect(mockCreateCommit).toHaveBeenCalledWith(mockOctokit, {
      owner: "test-owner",
      repo: "test-repo",
      branch: "dev-agent/ABC-123",
      message: "feat: implement ABC-123",
      files: [
        { path: "src/feature.ts", content: "export const x = 1;" },
        { path: "src/index.ts", content: "export * from './feature.js';" },
      ],
    });
  });

  it("should filter out delete operations", async () => {
    const stateWithDelete: DevWorkflowStateType = {
      ...baseState,
      files: [
        { path: "src/feature.ts", content: "export const x = 1;", operation: "create" },
        { path: "src/old.ts", content: "", operation: "delete" },
        { path: "src/updated.ts", content: "updated content", operation: "update" },
      ],
    };

    mockCreateCommit.mockResolvedValue({
      sha: "abc123",
      message: "feat: implement ABC-123",
      author: { name: "Agent", email: "agent@example.com", date: "2024-01-01" },
    });
    mockCreatePullRequest.mockResolvedValue({
      number: 42,
      title: "[ABC-123] Implement feature X",
      body: "Implements ABC-123",
      state: "open",
      headBranch: "dev-agent/ABC-123",
      baseBranch: "main",
      url: "https://github.com/test-owner/test-repo/pull/42",
    });
    mockUpdateIssueStatus.mockResolvedValue(undefined);
    mockEmitResponse.mockResolvedValue(undefined);

    const commitPRNode = createCommitPRNode(mockOctokit, mockLinearClient, config);
    await commitPRNode(stateWithDelete);

    // Should only include create and update, not delete
    expect(mockCreateCommit).toHaveBeenCalledWith(mockOctokit, {
      owner: "test-owner",
      repo: "test-repo",
      branch: "dev-agent/ABC-123",
      message: "feat: implement ABC-123",
      files: [
        { path: "src/feature.ts", content: "export const x = 1;" },
        { path: "src/updated.ts", content: "updated content" },
      ],
    });
  });

  it("should create PR with correct title and body", async () => {
    mockCreateCommit.mockResolvedValue({
      sha: "abc123",
      message: "feat: implement ABC-123",
      author: { name: "Agent", email: "agent@example.com", date: "2024-01-01" },
    });
    mockCreatePullRequest.mockResolvedValue({
      number: 42,
      title: "[ABC-123] Implement feature X",
      body: "Implements ABC-123\n\nGenerated by Dev Agent.",
      state: "open",
      headBranch: "dev-agent/ABC-123",
      baseBranch: "main",
      url: "https://github.com/test-owner/test-repo/pull/42",
    });
    mockUpdateIssueStatus.mockResolvedValue(undefined);
    mockEmitResponse.mockResolvedValue(undefined);

    const commitPRNode = createCommitPRNode(mockOctokit, mockLinearClient, config);
    await commitPRNode(baseState);

    expect(mockCreatePullRequest).toHaveBeenCalledWith(mockOctokit, {
      owner: "test-owner",
      repo: "test-repo",
      title: "[ABC-123] Implement feature X",
      body: "Implements ABC-123\n\nGenerated by Dev Agent.",
      head: "dev-agent/ABC-123",
      base: "main",
    });
  });

  it("should update Linear status to Done", async () => {
    mockCreateCommit.mockResolvedValue({
      sha: "abc123",
      message: "feat: implement ABC-123",
      author: { name: "Agent", email: "agent@example.com", date: "2024-01-01" },
    });
    mockCreatePullRequest.mockResolvedValue({
      number: 42,
      title: "[ABC-123] Implement feature X",
      body: "Implements ABC-123",
      state: "open",
      headBranch: "dev-agent/ABC-123",
      baseBranch: "main",
      url: "https://github.com/test-owner/test-repo/pull/42",
    });
    mockUpdateIssueStatus.mockResolvedValue(undefined);
    mockEmitResponse.mockResolvedValue(undefined);

    const commitPRNode = createCommitPRNode(mockOctokit, mockLinearClient, config);
    await commitPRNode(baseState);

    expect(mockUpdateIssueStatus).toHaveBeenCalledWith(
      mockLinearClient,
      "ABC-123",
      "Done"
    );
  });

  it("should emit response with PR link", async () => {
    mockCreateCommit.mockResolvedValue({
      sha: "abc123",
      message: "feat: implement ABC-123",
      author: { name: "Agent", email: "agent@example.com", date: "2024-01-01" },
    });
    mockCreatePullRequest.mockResolvedValue({
      number: 42,
      title: "[ABC-123] Implement feature X",
      body: "Implements ABC-123",
      state: "open",
      headBranch: "dev-agent/ABC-123",
      baseBranch: "main",
      url: "https://github.com/test-owner/test-repo/pull/42",
    });
    mockUpdateIssueStatus.mockResolvedValue(undefined);
    mockEmitResponse.mockResolvedValue(undefined);

    const commitPRNode = createCommitPRNode(mockOctokit, mockLinearClient, config);
    await commitPRNode(baseState);

    expect(mockEmitResponse).toHaveBeenCalledWith(
      mockLinearClient,
      "ABC-123",
      "Opened PR: https://github.com/test-owner/test-repo/pull/42"
    );
  });

  it("should return complete status", async () => {
    mockCreateCommit.mockResolvedValue({
      sha: "abc123",
      message: "feat: implement ABC-123",
      author: { name: "Agent", email: "agent@example.com", date: "2024-01-01" },
    });
    mockCreatePullRequest.mockResolvedValue({
      number: 42,
      title: "[ABC-123] Implement feature X",
      body: "Implements ABC-123",
      state: "open",
      headBranch: "dev-agent/ABC-123",
      baseBranch: "main",
      url: "https://github.com/test-owner/test-repo/pull/42",
    });
    mockUpdateIssueStatus.mockResolvedValue(undefined);
    mockEmitResponse.mockResolvedValue(undefined);

    const commitPRNode = createCommitPRNode(mockOctokit, mockLinearClient, config);
    const result = await commitPRNode(baseState);

    expect(result).toEqual({
      status: "complete",
      prNumber: 42,
    });
  });

  it("should propagate createCommit errors", async () => {
    mockCreateCommit.mockRejectedValue(new Error("Commit failed"));

    const commitPRNode = createCommitPRNode(mockOctokit, mockLinearClient, config);
    await expect(commitPRNode(baseState)).rejects.toThrow("Commit failed");
  });

  it("should propagate createPullRequest errors", async () => {
    mockCreateCommit.mockResolvedValue({
      sha: "abc123",
      message: "feat: implement ABC-123",
      author: { name: "Agent", email: "agent@example.com", date: "2024-01-01" },
    });
    mockCreatePullRequest.mockRejectedValue(new Error("PR creation failed"));

    const commitPRNode = createCommitPRNode(mockOctokit, mockLinearClient, config);
    await expect(commitPRNode(baseState)).rejects.toThrow("PR creation failed");
  });

  it("should handle single-line task description", async () => {
    const stateWithSingleLine: DevWorkflowStateType = {
      ...baseState,
      taskDescription: "Simple task",
    };

    mockCreateCommit.mockResolvedValue({
      sha: "abc123",
      message: "feat: implement ABC-123",
      author: { name: "Agent", email: "agent@example.com", date: "2024-01-01" },
    });
    mockCreatePullRequest.mockResolvedValue({
      number: 42,
      title: "[ABC-123] Simple task",
      body: "Implements ABC-123\n\nGenerated by Dev Agent.",
      state: "open",
      headBranch: "dev-agent/ABC-123",
      baseBranch: "main",
      url: "https://github.com/test-owner/test-repo/pull/42",
    });
    mockUpdateIssueStatus.mockResolvedValue(undefined);
    mockEmitResponse.mockResolvedValue(undefined);

    const commitPRNode = createCommitPRNode(mockOctokit, mockLinearClient, config);
    await commitPRNode(stateWithSingleLine);

    expect(mockCreatePullRequest).toHaveBeenCalledWith(mockOctokit, {
      owner: "test-owner",
      repo: "test-repo",
      title: "[ABC-123] Simple task",
      body: "Implements ABC-123\n\nGenerated by Dev Agent.",
      head: "dev-agent/ABC-123",
      base: "main",
    });
  });
});
