/**
 * Commit and PR Node
 *
 * LangGraph node that commits generated files and opens a pull request.
 * Uses factory pattern for dependency injection of config.
 *
 * This is the final node in the successful path of the dev workflow -
 * it commits the generated code, opens a PR, and updates Linear status to Done.
 */

import type { DevWorkflowStateType } from "@aesir/common";
import { generateCorrelationId } from "@aesir/common";
import { callMcpTool } from "../mcp/index.js";

const AGENT_ID = "dev-agent";

/**
 * GitHub repository configuration for commit and PR operations
 */
export interface CommitPRConfig {
  /** Repository owner (user or organization) */
  owner: string;
  /** Repository name */
  repo: string;
  /** Base branch for PR (default: 'main') */
  baseBranch: string;
}

/**
 * Factory function to create the commit/PR node with injected config.
 *
 * @param config - GitHub repository configuration
 * @returns LangGraph node function
 */
export function createCommitPRNode(config: CommitPRConfig) {
  /**
   * Commit and PR node - commits files and opens a pull request.
   *
   * @param state - Current workflow state with files and branch
   * @returns Partial state update with PR number and complete status
   */
  return async function commitPRNodeFn(
    state: DevWorkflowStateType,
  ): Promise<Partial<DevWorkflowStateType>> {
    const correlationId = generateCorrelationId("agent");

    // Convert FileChange[] to format for createCommit
    // Filter out delete operations (handled differently in Git Data API)
    const files = state.files
      .filter((f) => f.operation !== "delete")
      .map((f) => ({ path: f.path, content: f.content }));

    // Get first line of task description for PR title
    const titleLine = state.taskDescription.split("\n")[0] || state.taskId;

    // Ensure branchName is set
    const branchName = state.branchName ?? `task/${state.taskId}`;

    // Create commit with all files via MCP
    await callMcpTool({
      integration: "github",
      tool: "create_commit",
      params: {
        owner: config.owner,
        repo: config.repo,
        branch: branchName,
        message: `feat: implement ${state.taskId}`,
        files,
      },
      agentId: AGENT_ID,
      correlationId,
    });

    // Create pull request via MCP
    const pr = await callMcpTool<{ number: number; url: string }>({
      integration: "github",
      tool: "create_pull_request",
      params: {
        owner: config.owner,
        repo: config.repo,
        title: `[${state.taskId}] ${titleLine}`,
        body: `Implements ${state.taskId}\n\nGenerated by Dev Agent.`,
        head: branchName,
        base: config.baseBranch,
      },
      agentId: AGENT_ID,
      correlationId,
    });

    // Update Linear status to Done via MCP
    await callMcpTool({
      integration: "linear",
      tool: "update_issue_status",
      params: { issueId: state.taskId, statusName: "Done" },
      agentId: AGENT_ID,
      correlationId,
    });

    // TODO: emitResponse requires MCP tool - add 'emit_response' to Linear MCP
    // This is a UX feature that posts the PR link as a comment to the Linear issue.
    // Original call: emitResponse(linearClient, state.sessionId, `Opened PR: ${pr.url}`)
    // Context: Use sessionId (AgentSession ID) not taskId (Issue ID) when tool is added

    // Return state update with PR number for downstream consumers
    return {
      status: "complete",
      prNumber: pr.number,
    };
  };
}
