/**
 * Code Generation Tool
 *
 * LangChain tool for generating code based on task descriptions.
 * This tool structures the code generation request; the actual LLM
 * interaction is handled by the agent orchestration layer.
 *
 * Design decisions:
 * - Uses Zod schema for type-safe parameter validation
 * - Returns structured response with code, language, and explanation
 * - Integrates with logging infrastructure for observability
 * - Placeholder implementation - actual LLM call is in agent
 */

import { logger } from "@aesir/common";
import { tool } from "@langchain/core/tools";
import { z } from "zod";

/**
 * Supported programming languages for code generation
 */
export const SupportedLanguageSchema = z.enum([
  "typescript",
  "javascript",
  "python",
]);

export type SupportedLanguage = z.infer<typeof SupportedLanguageSchema>;

/**
 * Schema for code generation input parameters
 */
export const CodeGenInputSchema = z.object({
  taskDescription: z
    .string()
    .min(1, "Task description cannot be empty")
    .describe("Detailed description of what the code should do"),
  language: SupportedLanguageSchema.describe("Programming language to use"),
  context: z
    .string()
    .optional()
    .describe("Additional context like existing code or constraints"),
});

export type CodeGenInput = z.infer<typeof CodeGenInputSchema>;

/**
 * Schema for code generation output
 */
export const CodeGenOutputSchema = z.object({
  code: z.string().describe("The generated code"),
  language: SupportedLanguageSchema.describe("Language of the generated code"),
  explanation: z.string().describe("Explanation of what the code does"),
});

export type CodeGenOutput = z.infer<typeof CodeGenOutputSchema>;

/**
 * Generate a placeholder code snippet
 * This is a temporary implementation - actual LLM-based generation
 * will be handled by the agent
 */
function generatePlaceholderCode(
  taskDescription: string,
  language: SupportedLanguage,
): string {
  const commentSyntax = language === "python" ? "#" : "//";

  return `${commentSyntax} TODO: Implement ${taskDescription}
${commentSyntax} Generated by Aesir Code Generation Tool
${commentSyntax} Language: ${language}

${commentSyntax} Implementation placeholder
`;
}

/**
 * Code generation tool for the agent
 *
 * This tool structures code generation requests with proper validation.
 * The actual LLM-based code generation will be handled by the agent
 * orchestration layer, which has access to the full conversation context.
 */
export const codeGenTool = tool(
  async (rawInput): Promise<CodeGenOutput> => {
    // Schema handles validation; cast for TypeScript
    const { taskDescription, language, context } = rawInput as CodeGenInput;
    // Create a child logger with tool context
    const toolLogger = logger.child({
      tool: "generate_code",
      language,
    });

    // Log the tool invocation
    const timing = toolLogger.startTimer("tool_call", {
      context: {
        taskDescriptionLength: taskDescription.length,
        hasContext: context !== undefined && context.length > 0,
      },
      message: `Generating ${language} code for: ${taskDescription.slice(0, 100)}${taskDescription.length > 100 ? "..." : ""}`,
    });

    try {
      // Generate placeholder code
      // In the actual agent, the LLM will generate real code based on context
      const code = generatePlaceholderCode(taskDescription, language);

      const result: CodeGenOutput = {
        code,
        language,
        explanation: `Placeholder code for: ${taskDescription}. The actual implementation will be generated by the agent's LLM based on the full conversation context.`,
      };

      timing.success({
        context: { codeLength: code.length },
        message: "Code generation completed",
      });

      return result;
    } catch (error) {
      timing.failure({
        message:
          error instanceof Error ? error.message : "Unknown error occurred",
      });
      throw error;
    }
  },
  {
    name: "generate_code",
    description:
      "Generate code based on a task description. Use this to create new code files or functions. Returns generated code with explanation.",
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    schema: CodeGenInputSchema as any,
  },
);

/**
 * Type for the code generation tool
 */
export type CodeGenTool = typeof codeGenTool;
